join:
  - "<player> has entered the Embervale. The fire rises. 🔥🌄"
  - "A new Flameborn joins the fray. Welcome, <player>! 🛡️⚔️"
  - "<player> awakens. The Shroud shivers. 🌫️👀"
  - "<player> has joined the server. The Flame burns brighter! 🔥🕯️"
  - "<player> has returned from the ashes. 🔥🕊️"
  - "Flameborn detected: <player>. Let the cleansing begin. 🧼🔥"
  - "<player> is here. There’s *mushroom* for adventure. 🍄😁"
  - "<player> emerged from the Shroud... slightly moldier, but wiser. 🍄🧠"
  - "<player> has joined. Time to root out some evil. 🌱🗡️"
  - "Fungus beware — <player>'s here to spore trouble. 🍄💥"
  - "<player> just entered the Shroudlands. Good luck. ⚔️🌫️"
  - "The map grows brighter. <player> is online. 🗺️✨"
  - "<player> has joined. The lag may now commence. 🐢📡"
  - "Welcome <player> — please don't die to mushrooms. 🍄💀"
  - "Achievement unlocked for <player>: Joined the coolest server. 🏆🔥"
  - "<player> is such a fungi to hang out with! 🍄😎"
  - "I shiitake you not. <player> is here! 🍄😂"
  - "<player> is here! The Shroud's in deep shiitake now. 💩🍄"
  - "🔥 <player> has entered the server. Things are about to heat up! 🔥🔥"
  - "Burn, baby, burn! <player> just logged in. 🔥💃"
  - "<player> is lit. Literally. 🔥✨"
  - "<player> is bringing the heat! 🔥🧨"
  - "The Shroud just flinched. <player>'s flame is back. 🌫️🔥"
  - "It’s getting hot in here… <player>'s back. 🔥😅"
  - "From ember to inferno — <player> has joined. 🔥➡️🔥🔥"
  - "Hope you packed marshmallows. <player> just set up camp. 🔥⛺"
  - "<player> has joined. Lock up your loot and sharpen your blades! 🗡️🔥💰"
  - "<player> is bringing the pain! 🪓🛡️💢"
  - "<player> is here to cleave first and ask questions never. ⚔️😤"
  - "Trouble just got a name — and it’s <player>. 🏹⚔️😎"
  - "<player> has returned. The flame rises again. 🔥🕊️"
  - "The legend walks among us. Welcome, <player>. 🛡️📜"
  - "<player> has entered the battlefield. Let the hunt begin! ⚔️🧭"
  - "<player> joined. We're doomed. 😬💀"
  - "Oh no. They let <player> in again. 😱🚪"
  - "<player> just spawned in. No one make eye contact. 👀😳"
  - "The Shroud shivers. <player> is here to cleanse it. 🌫️✨"
  - "<player> is online. Things just got interesting. 👾🔌"
  - "Everyone act normal. <player> just joined. 😐😅"
  - "<player>. The prophecy is fulfilled. 🧙📖"
  - "A wild <player> appeared! 🎮👀"
  - "It’s dangerous to go alone. Good thing <player> showed up. 🗡️🛡️"
  - "Welcome, <player>. May your ping be low and your crits be high. 📡💥"
  - "<player> rises from the ashes. The Flame never dies. 🔥🐦"
  - "<player> has entered the fray. Brace for glory or ruin. 🛡️⚔️"
  - "The blade sings. The Shroud recoils. <player> is here. ⚔️🌫️"
  - "When all hope fades... <player> logs in. 🌩️🔥"
  - "It’s super effective! <player> joins the squad. 💥🎯"
  - "By the power of Greyskull! <player> has arrived. ⚡🗡️"
  - "The timeline just split. <player> logged in. ⏳🌀"
  - "Use the Flame, <player>. 🔥🧙"
  - "Guess who’s back. Back again. <player>'s back. Tell a friend. 🎶🙌"
  - "<player> is here. Nobody panic. Unless you're the Shroud. 🌫️😨"
  - "<player> walked in like they own the server. And honestly, we respect it. 😎🔥"
  - "Hey, look! It’s <player> — and they brought snacks. (Hopefully.) 🍿🍄"
  - "Things were quiet… too quiet. Then <player> arrived. 😏🔊"

leave:
  - "The fire dims. <player> has logged out. 🔥🌒"
  - "<player> fades into smoke and silence. 🌫️🤫"
  - "Farewell, <player>. The Flame awaits your return. 🔥🕊️"
  - "<player> has vanished into the Shroud. 🌫️💨"
  - "The Flame dims… <player> has left the server. 🕯️"
  - "<player> extinguished their torch and wandered off. 🔦🚶"
  - "<player>'s flame has flickered out... for now. 🔥💤"
  - "<player> left the server. The Shroud reclaims its turf. 🌫️🍄"
  - "<player> logged off — more *mushroom* for us! 🍄😋"
  - "<player> has gone dormant. Fungal growth resumes. 🌱🧟"
  - "Less fungi to hang out with. Bye <player>! 🍄👋"
  - "<player> disappeared over the nearest ridge. 🏞️🌫️"
  - "<player> rage-quit. The mushrooms won. 🍄😤"
  - "The lag won. <player> left the chat. 🐢📶"
  - "<player> has logged out. Cue dramatic music. 🎻🎬"
  - "BRB or RIP? <player> has left. 🤷💀"
  - "<player> has vanished. Insert mysterious puff of smoke here. 💨🧙"
  - "Server: “Did anyone see where <player> went?” 👀❓"
  - "<player> logged off… guess they *flamed out*. 🔥🚫"
  - "<player> burned too bright and vanished. 💥🔥"
  - "Ashes to ashes, dust to... BRB. <player> left. 🪦💨"
  - "Extinguished. <player> is offline. 🔥🛑"
  - "<player> has gone. They came, they spore, they conquered. 🍄🏆"
  - "<player> logged off — guess there wasn’t *mushroom* left. 🍄🏃"
  - "<player> left. Spore luck next time! 🍄✌️"
  - "<player> has fallen back into the Shroud. 🔥🌫️"
  - "<player> sheathed their sword and vanished into the fog. 🗡️🌫️"
  - "Another ember fades… Farewell, <player>. 🔥🕯️"
  - "<player> departs, but legends never truly leave. 📖🛡️"
  - "The hunt pauses. <player> has gone to rest. ⚔️🛏️"
  - "The battlefield falls silent. <player> is gone. ⚔️🌒"
  - "The world waits… until <player> returns. 🌍🕰️"
  - "<player> left the server. Sad face. 😢📴"
  - "<player> is gone. Time to loot their base. 🏚️💰"
  - "Peace out, <player>. May your snacks be crunchy and your queue times short. 🍿🎮"
  - "Server status: 20% less chaotic now that <player> is gone. 📉🌀"
  - "That was fun! <player> has left the chat. 🎉👋"
  - "<player> has left the party. Their story continues offline. 📖🌌"
  - "The last of their kind… <player> has disconnected. 🧝🔌"
  - "So long, and thanks for all the crits, <player>. 🐬💥"
  - "<player> vanished into the void. Roll credits. 🌌🎬"
  - "Game Over (for now). <player> has logged out. 🎮💀"
  - "<player> logged out. Respawning in… whenever. ⏳🌀"
  - "<player> left. Guess they ran out of mana. 🔮😴"
  - "Alt+F4 claimed another soul. Goodbye, <player>. ⚰️💻"
  - "The Flameborn <player> has left the chat. *fade to black* 🎭🔥"

